apiVersion: v1
kind: Service
metadata:
  labels:
    name: redginx 
    role: service
  name: redginx
  namespace: ingress-redginx
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: "redginx"
  type: LoadBalancer