apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
  namespace: ingress-redginx
spec:
  replicas: 1
  selector:
    name: redis-master
  template:
    metadata:
      labels:
        name: redis-master
        redis-master: "true"
        role: master
    spec:
      initContainers:
      - name: fix-volume-permission
        image: busybox
        command:
        - sh
        - -c
        - chown -R 1001:1001 /bitnami/redis/data/
        securityContext:
          privileged: true
        volumeMounts:
        - name: redis-data
          mountPath: /bitnami/redis/data/
      containers:
      - name: redis-master
        image: bitnami/redis:4.0.10
        env:
          - name: ALLOW_EMPTY_PASSWORD
            value: "yes"
          - name: REDIS_REPLICATION_MODE
            value: "master"
        volumeMounts:
          - mountPath: /bitnami/redis/data/
            name: redis-data
        ports:    
          - containerPort: 6379
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-master-data